### PR TITLE
Port to oci-spec 0.7

### PR DESCRIPTION
**Pull request by cgwalters**
Now we can use a proper Digest type.

### CODE REVIEW

**Comment by cgwalters** [comment]
CI here can't succeed on semver-incompat bumps, though what I could do is prep the PR for ostree-rs-ext in advance, and point CI at it temporarily

**Comment by jeckersb** [comment]
> CI here can't succeed on semver-incompat bumps, though what I could do is prep the PR for ostree-rs-ext in advance, and point CI at it temporarily

Yeah I was just looking into that.  Wrapping my head around the dependency graph of things in CI.  I started on porting ostree-rs-ext over to ocidir 0.3.0 which if I'm following is required to untangle all of this.

**Comment by cgwalters** [comment]
Ah ok I'd started looking at it too, what I have so far is

```
diff --git a/lib/Cargo.toml b/lib/Cargo.toml
index 0cce26e9..a00490d6 100644
--- a/lib/Cargo.toml
+++ b/lib/Cargo.toml
@@ -13,7 +13,7 @@ rust-version = "1.74.0"
 # Note that we re-export the oci-spec types
 # that are exported by this crate, so when bumping
 # semver here you must also bump our semver.
-containers-image-proxy = "0.6.0"
+containers-image-proxy = { path = "../../../containers/containers-image-proxy-rs" }
 # We re-export this library too.
 ostree = { features = ["v2022_6"], version = "0.19.0" }
 
@@ -36,7 +36,7 @@ once_cell = "1.9"
 libc = "0.2.92"
 libsystemd = "0.7.0"
 openssl = "0.10.33"
-ocidir = "0.2.0"
+ocidir = "0.3.0"
 pin-project = "1.0"
 regex = "1.5.4"
 rustix = { version = "0.38", features = ["fs", "process"] }
diff --git a/lib/src/cli.rs b/lib/src/cli.rs
index 6bbfcdf2..fcb1d977 100644
--- a/lib/src/cli.rs
+++ b/lib/src/cli.rs
@@ -594,7 +594,12 @@ pub fn layer_progress_format(p: &ImportProgress) -> String {
         ImportProgress::DerivedLayerCompleted(v) => (false, "layer", v),
     };
     // podman outputs 12 characters of digest, let's add 7 for `sha256:`.
-    let short_digest = layer.digest().chars().take(12 + 7).collect::<String>();
+    let short_digest = layer
+        .digest()
+        .digest()
+        .chars()
+        .take(12 + 7)
+        .collect::<String>();
     if starting {
         let size = glib::format_size(layer.size() as u64);
         format!("Fetching {s} {short_digest} ({size})")
@@ -934,7 +939,7 @@ async fn container_history(repo: &ostree::Repo, imgref: &ImageReference) -> Resu
 
         let mut remaining = width;
 
-        let digest = layer.digest().as_str();
+        let digest = layer.digest().digest();
         // Verify it's OK to slice, this should all be ASCII
         assert!(digest.chars().all(|c| c.is_ascii()));
         let digest_max = columns[0].1;
diff --git a/lib/src/container/encapsulate.rs b/lib/src/container/encapsulate.rs
index e7964fcf..d2b84ba2 100644
--- a/lib/src/container/encapsulate.rs
+++ b/lib/src/container/encapsulate.rs
@@ -151,7 +151,10 @@ pub(crate) fn export_chunked(
 
     // This label (mentioned above) points to the last layer that is part of
     // the ostree commit.
-    labels.insert(DIFFID_LABEL.into(), format!("sha256:{}", last_digest));
+    labels.insert(
+        DIFFID_LABEL.into(),
+        format!("sha256:{}", last_digest.digest()),
+    );
     Ok(())
 }
 
diff --git a/lib/src/container/mod.rs b/lib/src/container/mod.rs
index 3c7f2929..ea4f2255 100644
--- a/lib/src/container/mod.rs
+++ b/lib/src/container/mod.rs
@@ -341,12 +341,12 @@ impl<'a> ManifestDiff<'a> {
         let src_layers = src
             .layers()
             .iter()
-            .map(|l| (l.digest(), l))
+            .map(|l| (l.digest().digest(), l))
             .collect::<HashMap<_, _>>();
         let dest_layers = dest
             .layers()
             .iter()
-            .map(|l| (l.digest(), l))
+            .map(|l| (l.digest().digest(), l))
             .collect::<HashMap<_, _>>();
         let mut removed = Vec::new();
         let mut added = Vec::new();
@@ -355,13 +355,13 @@ impl<'a> ManifestDiff<'a> {
                 removed.push(descriptor);
             }
         }
-        removed.sort_by(|a, b| a.digest().cmp(b.digest()));
+        removed.sort_by(|a, b| a.digest().digest().cmp(b.digest().digest()));
         for (blobid, &descriptor) in dest_layers.iter() {
             if !src_layers.contains_key(blobid) {
                 added.push(descriptor);
             }
         }
-        added.sort_by(|a, b| a.digest().cmp(b.digest()));
+        added.sort_by(|a, b| a.digest().digest().cmp(b.digest().digest()));
 
         fn layersum<'a, I: Iterator<Item = &'a oci_spec::image::Descriptor>>(layers: I) -> u64 {
             layers.map(|layer| layer.size() as u64).sum()
diff --git a/lib/src/container/store.rs b/lib/src/container/store.rs
index 7f51e3f0..bed35703 100644
--- a/lib/src/container/store.rs
+++ b/lib/src/container/store.rs
@@ -21,7 +21,7 @@ use flate2::Compression;
 use fn_error_context::context;
 use futures_util::TryFutureExt;
 use oci_spec::image::{
-    self as oci_image, Arch, Descriptor, History, ImageConfiguration, ImageManifest,
+    self as oci_image, Arch, Descriptor, Digest, History, ImageConfiguration, ImageManifest,
 };
 use ostree::prelude::{Cast, FileEnumeratorExt, FileExt, ToVariant};
 use ostree::{gio, glib};
@@ -68,7 +68,7 @@ fn ref_for_blob_digest(d: &str) -> Result<String> {
 
 /// Convert e.g. sha256:12345... into `/ostree/container/blob/sha256_2B12345...`.
 fn ref_for_layer(l: &oci_image::Descriptor) -> Result<String> {
-    ref_for_blob_digest(l.digest().as_str())
+    ref_for_blob_digest(&l.digest().to_string())
 }
 
 /// Convert e.g. sha256:12345... into `/ostree/container/blob/sha256_2B12345...`.
@@ -199,18 +199,6 @@ pub struct ManifestLayerState {
     pub commit: Option<String>,
 }
 
-impl ManifestLayerState {
-    /// The cryptographic checksum.
-    pub fn digest(&self) -> &str {
-        self.layer.digest().as_str()
-    }
-
-    /// The (possibly compressed) size.
-    pub fn size(&self) -> u64 {
-        self.layer.size() as u64
-    }
-}
-
 /// Information about which layers need to be downloaded.
 #[derive(Debug)]
 pub struct PreparedImport {
@@ -286,7 +274,7 @@ impl PreparedImport {
                     if v.commit.is_some() {
                         (stored + 1, to_fetch, sz)
                     } else {
-                        (stored, to_fetch + 1, sz + v.size())
+                        (stored, to_fetch + 1, sz + v.layer.size())
                     }
                 });
         (to_fetch > 0).then(|| {
@@ -638,7 +626,7 @@ impl ImageImporter {
         }
 
         let (manifest_digest, manifest) = self.proxy.fetch_manifest(&self.proxy_img).await?;
-        let new_imageid = manifest.config().digest().as_str();
+        let new_imageid = manifest.config().digest();
 
         // Query for previous stored state
 
@@ -649,7 +637,7 @@ impl ImageImporter {
                     return Ok(PrepareResult::AlreadyPresent(previous_state));
                 }
                 // Failing that, if they have the same imageID, we're also done.
-                let previous_imageid = previous_state.manifest.config().digest().as_str();
+                let previous_imageid = previous_state.manifest.config().digest();
                 if previous_imageid == new_imageid {
                     return Ok(PrepareResult::AlreadyPresent(previous_state));
                 }
```

**Comment by cgwalters** [comment]
@jeckersb this is ready now, I pointed CI at your branch in https://github.com/ostreedev/ostree-rs-ext/pull/663

Then we can release this crate and change your PR to use the published crate, then when we publish ostree-rs-ext we can change this to reference the published version of that...

**Review by jeckersb — APPROVED** [review]

**Pull request merged**
